#############################################################################
# Makefile for building: nunchuck
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Mar 17 14:43:17 2011
# Project:  nunchuck.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile nunchuck.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Itrash -Isubmit/junk1 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Appl.c \
		i2c-dev-async.c \
		i2c-dev-async.mod.c \
		i2cbusses.c \
		i2cdetect.c \
		i2cdump.c \
		i2cget.c \
		i2cset.c \
		moving_pt.c \
		queue.c \
		user_appli.c \
		util.c \
		i2c_appl/Appl(3).c \
		i2c_appl/Appl.c \
		i2c_appl/i2c-dev-async.c \
		i2c_appl/i2cbusses.c \
		i2c_appl/i2cdetect.c \
		i2c_appl/i2cdump.c \
		i2c_appl/i2cget.c \
		i2c_appl/i2cset.c \
		i2c_appl/util.c \
		submit/i2c-dev-async.c \
		submit/i2c-dev-async.mod.c \
		trash/Appl_old.c \
		trash/i2c-dev-async_v37.c \
		trash/i2c-dev_raw.c \
		trash/i2c_dev_asyn.c \
		trash/opengl_ex.c \
		trash/vga_test.c \
		trash/vga_test2.c \
		submit/junk1/queue.cpp \
		submit/junk1/user_appli.cpp \
		submit/junk1/widget.cpp \
		submit/user_files/queue.cpp \
		submit/user_files/user_appli.cpp \
		submit/user_files/widget.cpp moc_widget.cpp
OBJECTS       = Appl.o \
		i2c-dev-async.o \
		i2c-dev-async.mod.o \
		i2cbusses.o \
		i2cdetect.o \
		i2cdump.o \
		i2cget.o \
		i2cset.o \
		moving_pt.o \
		queue.o \
		user_appli.o \
		util.o \
		Appl(3).o \
		Appl.o \
		i2c-dev-async.o \
		i2cbusses.o \
		i2cdetect.o \
		i2cdump.o \
		i2cget.o \
		i2cset.o \
		util.o \
		i2c-dev-async.o \
		i2c-dev-async.mod.o \
		Appl_old.o \
		i2c-dev-async_v37.o \
		i2c-dev_raw.o \
		i2c_dev_asyn.o \
		opengl_ex.o \
		vga_test.o \
		vga_test2.o \
		queue.o \
		user_appli.o \
		widget.o \
		queue.o \
		user_appli.o \
		widget.o \
		moc_widget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		nunchuck.pro
QMAKE_TARGET  = nunchuck
DESTDIR       = 
TARGET        = nunchuck

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nunchuck.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile nunchuck.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile nunchuck.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nunchuck1.0.0 || $(MKDIR) .tmp/nunchuck1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nunchuck1.0.0/ && $(COPY_FILE) --parents i2c-dev.h i2cbusses.h moving_pt.h queue.h user_appli.h util.h i2c_appl/i2c-dev.h i2c_appl/i2cbusses.h i2c_appl/util.h trash/SimpleDraw.h submit/junk1/i2c-dev.h submit/junk1/queue.h submit/junk1/ui_widget.h submit/junk1/user_appli.h submit/junk1/widget.h submit/user_files/i2c-dev.h submit/user_files/queue.h submit/user_files/ui_widget.h submit/user_files/user_appli.h submit/user_files/widget.h .tmp/nunchuck1.0.0/ && $(COPY_FILE) --parents Appl.c i2c-dev-async.c i2c-dev-async.mod.c i2cbusses.c i2cdetect.c i2cdump.c i2cget.c i2cset.c moving_pt.c queue.c user_appli.c util.c i2c_appl/Appl(3).c i2c_appl/Appl.c i2c_appl/i2c-dev-async.c i2c_appl/i2cbusses.c i2c_appl/i2cdetect.c i2c_appl/i2cdump.c i2c_appl/i2cget.c i2c_appl/i2cset.c i2c_appl/util.c submit/i2c-dev-async.c submit/i2c-dev-async.mod.c trash/Appl_old.c trash/i2c-dev-async_v37.c trash/i2c-dev_raw.c trash/i2c_dev_asyn.c trash/opengl_ex.c trash/vga_test.c trash/vga_test2.c submit/junk1/queue.cpp submit/junk1/user_appli.cpp submit/junk1/widget.cpp submit/user_files/queue.cpp submit/user_files/user_appli.cpp submit/user_files/widget.cpp .tmp/nunchuck1.0.0/ && (cd `dirname .tmp/nunchuck1.0.0` && $(TAR) nunchuck1.0.0.tar nunchuck1.0.0 && $(COMPRESS) nunchuck1.0.0.tar) && $(MOVE) `dirname .tmp/nunchuck1.0.0`/nunchuck1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nunchuck1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_widget.cpp
moc_widget.cpp: submit/junk1/queue.h \
		submit/junk1/user_appli.h \
		submit/junk1/i2c-dev.h \
		submit/junk1/widget.h \
		submit/junk1/widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) submit/junk1/widget.h -o moc_widget.cpp

moc_widget.cpp: submit/user_files/queue.h \
		submit/user_files/user_appli.h \
		submit/user_files/i2c-dev.h \
		submit/user_files/widget.h \
		submit/user_files/widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) submit/user_files/widget.h -o moc_widget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Appl.o: Appl.c i2c-dev.h \
		i2cbusses.h \
		util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Appl.o Appl.c

i2c-dev-async.o: i2c-dev-async.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async.o i2c-dev-async.c

i2c-dev-async.mod.o: i2c-dev-async.mod.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async.mod.o i2c-dev-async.mod.c

i2cbusses.o: i2cbusses.c i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cbusses.o i2cbusses.c

i2cdetect.o: i2cdetect.c i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cdetect.o i2cdetect.c

i2cdump.o: i2cdump.c i2cbusses.h \
		util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cdump.o i2cdump.c

i2cget.o: i2cget.c i2cbusses.h \
		util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cget.o i2cget.c

i2cset.o: i2cset.c i2cbusses.h \
		util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cset.o i2cset.c

moving_pt.o: moving_pt.c moving_pt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o moving_pt.o moving_pt.c

queue.o: queue.c queue.h \
		user_appli.h \
		i2c-dev.h \
		i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o queue.o queue.c

user_appli.o: user_appli.c user_appli.h \
		i2c-dev.h \
		i2cbusses.h \
		queue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o user_appli.o user_appli.c

util.o: util.c util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o util.o util.c

Appl(3).o: i2c_appl/Appl(3).c i2c_appl/i2c-dev.h \
		i2c_appl/i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Appl(3).o i2c_appl/Appl(3).c

Appl.o: i2c_appl/Appl.c i2c_appl/i2c-dev.h \
		i2c_appl/i2cbusses.h \
		i2c_appl/util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Appl.o i2c_appl/Appl.c

i2c-dev-async.o: i2c_appl/i2c-dev-async.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async.o i2c_appl/i2c-dev-async.c

i2cbusses.o: i2c_appl/i2cbusses.c i2c_appl/i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cbusses.o i2c_appl/i2cbusses.c

i2cdetect.o: i2c_appl/i2cdetect.c i2c_appl/i2cbusses.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cdetect.o i2c_appl/i2cdetect.c

i2cdump.o: i2c_appl/i2cdump.c i2c_appl/i2cbusses.h \
		i2c_appl/util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cdump.o i2c_appl/i2cdump.c

i2cget.o: i2c_appl/i2cget.c i2c_appl/i2cbusses.h \
		i2c_appl/util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cget.o i2c_appl/i2cget.c

i2cset.o: i2c_appl/i2cset.c i2c_appl/i2cbusses.h \
		i2c_appl/util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2cset.o i2c_appl/i2cset.c

util.o: i2c_appl/util.c i2c_appl/util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o util.o i2c_appl/util.c

i2c-dev-async.o: submit/i2c-dev-async.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async.o submit/i2c-dev-async.c

i2c-dev-async.mod.o: submit/i2c-dev-async.mod.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async.mod.o submit/i2c-dev-async.mod.c

Appl_old.o: trash/Appl_old.c i2c-dev.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Appl_old.o trash/Appl_old.c

i2c-dev-async_v37.o: trash/i2c-dev-async_v37.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev-async_v37.o trash/i2c-dev-async_v37.c

i2c-dev_raw.o: trash/i2c-dev_raw.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c-dev_raw.o trash/i2c-dev_raw.c

i2c_dev_asyn.o: trash/i2c_dev_asyn.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o i2c_dev_asyn.o trash/i2c_dev_asyn.c

opengl_ex.o: trash/opengl_ex.c trash/SimpleDraw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o opengl_ex.o trash/opengl_ex.c

vga_test.o: trash/vga_test.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o vga_test.o trash/vga_test.c

vga_test2.o: trash/vga_test2.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o vga_test2.o trash/vga_test2.c

queue.o: submit/junk1/queue.cpp submit/junk1/queue.h \
		submit/junk1/user_appli.h \
		submit/junk1/i2c-dev.h \
		submit/junk1/widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queue.o submit/junk1/queue.cpp

user_appli.o: submit/junk1/user_appli.cpp submit/junk1/widget.h \
		submit/junk1/queue.h \
		submit/junk1/user_appli.h \
		submit/junk1/i2c-dev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_appli.o submit/junk1/user_appli.cpp

widget.o: submit/junk1/widget.cpp submit/junk1/widget.h \
		submit/junk1/queue.h \
		submit/junk1/user_appli.h \
		submit/junk1/i2c-dev.h \
		submit/junk1/ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o submit/junk1/widget.cpp

queue.o: submit/user_files/queue.cpp submit/user_files/queue.h \
		submit/user_files/user_appli.h \
		submit/user_files/i2c-dev.h \
		submit/user_files/widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queue.o submit/user_files/queue.cpp

user_appli.o: submit/user_files/user_appli.cpp submit/user_files/widget.h \
		submit/user_files/queue.h \
		submit/user_files/user_appli.h \
		submit/user_files/i2c-dev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_appli.o submit/user_files/user_appli.cpp

widget.o: submit/user_files/widget.cpp submit/user_files/widget.h \
		submit/user_files/queue.h \
		submit/user_files/user_appli.h \
		submit/user_files/i2c-dev.h \
		submit/user_files/ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o submit/user_files/widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

