######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 17 16:28:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += i2c-dev.h queue.h ui_widget.h user_appli.h widget.h
SOURCES += queue.cpp user_appli.cpp widget.cpp
